services:
  joern:
    image: local-joern:latest
    container_name: ${JOERN_CONTAINER_NAME}
    ports:
      - "${JOERN_PORT}:9000"
    volumes:
      - ${HOST_SOURCE_ROOT}:${CONTAINER_SOURCE_ROOT}
      - ${HOST_WORKSPACE_ROOT}:${CONTAINER_WORKSPACE_ROOT}
    command: ["--server-port", "9000", "--server-host", "0.0.0.0"]